package com.elementaryengineers.fwc.model;

/**
 * Created by sarahakk on 4/26/16.
 */
public enum Page {
    ADMIN_REGISTRATION,
    LOGIN,
    FORGOT_PASSWORD,
    ADMIN_RESET_PASSWORD,
    MY_ACCOUNT,
    ADMIN_HOME,
    TEACHER_PROFILE,
    ADMIN_MANAGE_PASSWORDS,
    TEACHER_REGISTRATION,
    TEACHER_HOME,
    TUTORIALS,
    TEACHER_HISTORY,
    CLASSES,
    NEW_CLASS,
    STUDENT_REGISTRATION,
    EDIT_CLASS,
    CLASS_ROSTER,
    STUDENT_PROFILE,
    TEACHER_STUDENT_HISTORY,
    TEACHER_MANAGE_PASSWORDS,
    STUDENT_HOME,
    STUDENT_HISTORY
}